### ISSUE TITLE
Documentation need update

### ISSUE THREAD

**Issue by rolfcronberg** [Cisco-Talos/clamav-safebrowsing#6]
I have downloaded, installed and tested this software and it seem to work as expected. One thing that made me loose time was that it wasn't documented how much memory I needed to to the first sync. 

I started with 6 GB memory and it took for ever and eventually I ran out of memory. After increasing memory to 12 GB och 6 GB swap the first sync went a lot faster och completed well. After the first sync, the following are a lot faster. 

Please update documentation with this so that others wont have to spend time like I had to. 

With best regards
Rolf

**Comment by val-ms** [comment]
@rolfcronberg How's this? https://github.com/Cisco-Talos/clamav-safebrowsing/commit/bcc46768b74c34fe806c4123cf792a47b79eca34

**Comment by rolfcronberg** [comment]
Yes, that is better. It would have helped me. 

Thank you!
